### ISSUE TITLE
AhuUid UUID element missing

### ISSUE THREAD

**Issue by ovord** [openflightmaps/ofmx#20]
```
  <AhuUid>
    <AhpUid region="EB">
      <codeId>EBAW</codeId>
    </AhpUid>
  </AhuUid>
```

There is no element iin the AhuUid node

**Comment by svoop** [comment]
@ovord

Ich verstehe dich nicht ganz: Du kannst für jedes beliebige `*Uid` eine UUID errechnen [indem du dieser Anleitung folgst](https://github.com/openflightmaps/ofmx/wiki/Identifiers#mid) und dann als Attribut `@mid` dranheften. In diesem Fall würde es dann so aussehen:

```xml
<AhuUid>
  <AhpUid region="EB" mid="cb88eef2-3ed1-0dd9-d8d6-e4d7743943a8">
    <codeId>EBAW</codeId>
  </AhpUid>
</AhuUid>
```

Die UUID wird in diesem Beispiel hergeleitet vom String `AhuUid|EB|EBAW`, du kannst es mit [mit diesem JSFiddle](http://jsfiddle.net/6ehuksoq/12/) ausprobieren.

Beantwortet das dein Anliegen oder habe ich etwas nicht richtig verstanden?
