### ISSUE TITLE
AIXM schema imported in DOS format / should probably be changed

### ISSUE THREAD

**Issue by philhug** [openflightmaps/ofmx#3]
Is this deliberate?

**Comment by svoop** [comment]
@philhug 

> AIXM schema imported in DOS format

I don't understand, can you elaborate the issue a little?

**Comment by philhug** [comment]
user@unknown:~/dev/ofm/ofmx/schema/4.5-0$ file OFMX-*
OFMX-DataTypes.xsd: XML 1.0 document, UTF-8 Unicode text, with very long lines, with CRLF line terminators
OFMX-Features.xsd:  XML 1.0 document, ASCII text, with CRLF line terminators
OFMX-Snapshot.xsd:  XML 1.0 document, ASCII text
OFMX-Update.xsd:    XML 1.0 document, ASCII text, with CRLF line terminators

user@unknown:~/dev/ofm/ofmx/schema/4.5-1$ file *
OFMX-DataTypes.xsd: XML 1.0 document, UTF-8 Unicode text, with very long lines, with CRLF line terminators
OFMX-Features.xsd:  XML 1.0 document, ASCII text, with CRLF line terminators
OFMX-Snapshot.xsd:  XML 1.0 document, ASCII text

OFMX-Snapshot.xsd is fine, but the others have CRLF line terminators

**Comment by svoop** [comment]
Es wäre mir auch lieber, die Files aufzuräumen (Returns, Spaces statt Tabs etc). Das Problem dabei ist aber, dass ein `diff` mehr auf die Original-AIXM-Schema kein brauchbares Resultat mehr liefert. Darum (und auch wenn's weh tut), ist es besser, beim AIXM-Murks zu bleiben. Ich stelle aber noch ein `.editorconfig` daneben.
