### ISSUE TITLE
Move @region into Uid

### ISSUE THREAD

**Issue by philhug** [openflightmaps/ofmx#4]
The draft specification allows this attribute to be present on e.g. the Ahb object.
```
<Ase region="LF" source="ENR|2.3|5|9472" classLayers="2">
  <AseUid>
    <codeType>TMA</codeType>
    <codeId>1</codeId>
  </AseUid>
  <txtLocalType>SBT</txtLocalType>
...
```
[more](https://github.com/openflightmaps/ofmx/wiki/Airspace#ase-airspace)

Instead it should only be put into the corresponding Uid element like this:
```
<Ase source="ENR|2.3|5|9472" classLayers="2">
  <AseUid region="LF">
    <codeType>TMA</codeType>
    <codeId>1</codeId>
  </AseUid>
  <txtLocalType>SBT</txtLocalType>
...
```

The rationale for this: The AseUid element should even the the absence of the mid="" attribute uniquely identify the object within the whole database. (e.g. by hashing the keys)
To accomplish this, when more than one country is installed in the same database / xml the region needs to be included in the key.

See also the example on the identifiers page:
https://github.com/openflightmaps/ofmx/wiki/Identifiers

TBD: source might also be moved into Uid, but if it doesn't have to be part of the hash.

**Comment by svoop** [comment]
Done with commit b97c0022
