### ISSUE TITLE
AIXM to OFMX Mapping/migration

### ISSUE THREAD

**Issue by ovord** [openflightmaps/ofmx#9]
How to code Info Frequencies in Units, as the codeType INFO doesn't exist any more? @svoop

**Comment by svoop** [comment]
A `Uni` Unit e.g. of codeType OTHER can have a `Ser` Service of codeType INFO with one or more `Fqy` Frequency attached.

Please note that for very large value lists such as codeType, the OFMX docs don't always list all available options. (I've selected the most common ones according to the EAD dump.) However, if the listing is incomplete, there's a "full list" link to get all available values.
